on:
  pull_request:
    types: [opened, synchronize]

name: ChatGPT CodeReview

jobs:
  chatgpt_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.CHATGPT_SESSION_TOKEN }}
          # Optional
          LANGUAGE: Korean
          top_p: 1
          temperature: 1
